version: '3.8'

services:
  emergency-web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: local_pgdb
    networks:
      - external-emergency-network

networks:
  external-emergency-network:
    external: true