version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=telegraf_user
      - INFLUXDB_USER_PASSWORD=password
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

volumes:
  influxdbv2: