version: "3.8"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SETUP_EMAIL: user-name@domain-name.com
      PGADMIN_SETUP_PASSWORD: strong-password
      PGADMIN_SERVER_PORT: 5432
      PGADMIN_SERVER_HOST: local_pgdb  # Utilisez le nom du service du conteneur PostgreSQL comme hôte
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
