version: '3.8'

services:
  simulator-view:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge
